// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFDPqHTVcYpTzHBDLHrJ5ET5N3Pp-QNX4',
    appId: '1:16483934656:web:3fd79597b577722d6b6825',
    messagingSenderId: '16483934656',
    projectId: 'coins-store-799b6',
    authDomain: 'coins-store-799b6.firebaseapp.com',
    storageBucket: 'coins-store-799b6.firebasestorage.app',
    measurementId: 'G-ZJN4EQP17S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtYOHfieRNjj5f0cMtqze75OZjSApbpMg',
    appId: '1:16483934656:android:c687524857f911c56b6825',
    messagingSenderId: '16483934656',
    projectId: 'coins-store-799b6',
    storageBucket: 'coins-store-799b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjBUEfrugxSovW3eJUMYL35vRQBWX1wbc',
    appId: '1:16483934656:ios:082d56f378ecdc196b6825',
    messagingSenderId: '16483934656',
    projectId: 'coins-store-799b6',
    storageBucket: 'coins-store-799b6.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjBUEfrugxSovW3eJUMYL35vRQBWX1wbc',
    appId: '1:16483934656:ios:082d56f378ecdc196b6825',
    messagingSenderId: '16483934656',
    projectId: 'coins-store-799b6',
    storageBucket: 'coins-store-799b6.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFDPqHTVcYpTzHBDLHrJ5ET5N3Pp-QNX4',
    appId: '1:16483934656:web:b8e9312727e97eaf6b6825',
    messagingSenderId: '16483934656',
    projectId: 'coins-store-799b6',
    authDomain: 'coins-store-799b6.firebaseapp.com',
    storageBucket: 'coins-store-799b6.firebasestorage.app',
    measurementId: 'G-ESBWT7KRC7',
  );
}
